import { ItemCollection } from '@src/models/itemCollection.model';
import { mockApiCallTime } from '@src/utils/mock.utils';

export const getCollection = async (): Promise<ItemCollection[]> => {
  await mockApiCallTime();

  return [
    {
      id: 'caaacfc1-46ca-4147-ac23-4dc0a31dd39d',
      name: 'semper',
      character: 'Herschel Beedon',
      type: 3,
      manufacturer: 'Sandy Pridgeon',
      chassisDesigner: 'Toddie Beneyto',
      state: 2,
      apparition: 'Maxed Out: Hard Times, Easy Credit and the Era of Predatory Lenders',
      color: 'crimson',
    },
    {
      id: '5ccf014a-310f-4e4b-8bd8-e330d61faa63',
      name: 'at',
      character: 'Amie Kalkofer',
      type: 2,
      manufacturer: 'Dun McRory',
      chassisDesigner: 'Louise Dunnet',
      state: 3,
      apparition: 'Body Count',
      color: 'goldenrod',
    },
    {
      id: '6c4d2063-2ef2-467b-a11f-2b140815735d',
      name: 'at',
      character: 'Dara Diter',
      type: 1,
      manufacturer: 'Connie Polley',
      chassisDesigner: 'Ailene Orleton',
      state: 5,
      apparition: 'In My Skin (Dans ma Peau)',
      color: 'crimson',
    },
    {
      id: '623f8b79-0846-4cf4-8a85-f1012080693b',
      name: 'interdum',
      character: 'Izak Walliker',
      type: 2,
      manufacturer: 'Alec Wakeley',
      chassisDesigner: 'Marilin Penvarne',
      state: 3,
      apparition: 'Elvis and Me',
      color: 'teal',
    },
    {
      id: '9240eb17-0dbe-41d3-a2eb-86512ab617cf',
      name: 'a',
      character: 'Sher Babcock',
      type: 3,
      manufacturer: 'Margalo Sharer',
      chassisDesigner: 'Nehemiah Schrinel',
      state: 4,
      apparition: 'Reincarnation',
      color: 'blue',
    },
    {
      id: 'fd6d17d8-2a4d-4565-b19d-c0e57a6357de',
      name: 'pede',
      character: 'Vikky Jentle',
      type: 1,
      manufacturer: 'Esmaria Wraighte',
      chassisDesigner: 'Sabra Habron',
      state: 6,
      apparition: 'Kozara',
      color: 'orange',
    },
    {
      id: 'f00a4397-e50f-4ada-bc3c-a89412eaefe2',
      name: 'at',
      character: 'Gerrie Knappe',
      type: 2,
      manufacturer: 'Dorene Fernant',
      chassisDesigner: 'Gustie Zima',
      state: 3,
      apparition: 'Dark Journey',
      color: 'mauv',
    },
    {
      id: 'c85ea96a-e105-4b4f-9fea-9a000bc37d17',
      name: 'amet',
      character: 'Shalna Livock',
      type: 2,
      manufacturer: 'Jacqui Griffe',
      chassisDesigner: 'Lurlene Nusche',
      state: 4,
      apparition: 'Attack the Block',
      color: 'maroon',
    },
    {
      id: 'fb481262-e14e-45ae-b74b-6fe0a737381c',
      name: 'et',
      character: 'Kylynn Placide',
      type: 3,
      manufacturer: 'Carolan Kirvell',
      chassisDesigner: 'Morton Clavey',
      state: 1,
      apparition: 'Culture High, The',
      color: 'fuscia',
    },
    {
      id: '80245cd5-d9c9-468a-b245-191233c8aaed',
      name: 'varius',
      character: 'Caesar Banane',
      type: 1,
      manufacturer: 'Michael Older',
      chassisDesigner: 'Arv Damiral',
      state: 1,
      apparition: "Porky's II: The Next Day",
      color: 'mauv',
    },
    {
      id: '1c36e77c-b5f1-45be-b5b5-f862a307d64f',
      name: 'amet',
      character: 'Griff Bang',
      type: 1,
      manufacturer: 'Janessa Billborough',
      chassisDesigner: 'Kenon Shoebottom',
      state: 6,
      apparition: 'Tiger from Tjampa, The (Harimau Tjampa)',
      color: 'yellow',
    },
    {
      id: '57a03d29-9ad0-4748-a7ba-41d784f81118',
      name: 'nisi',
      character: 'Marilin Manjot',
      type: 1,
      manufacturer: 'Joellen Kiehne',
      chassisDesigner: 'Gherardo Dobrovolski',
      state: 7,
      apparition: 'Maniac',
      color: 'pink',
    },
    {
      id: '526e075c-1234-4e3f-8e47-46dff7e9f7df',
      name: 'eu',
      character: 'York Leonards',
      type: 2,
      manufacturer: 'Darrelle Zanutti',
      chassisDesigner: 'Jody Walasik',
      state: 4,
      apparition: 'Standard Operating Procedure',
      color: 'blue',
    },
    {
      id: '4c26ffc3-befe-4fd2-b48e-cbef5b52d688',
      name: 'amet',
      character: 'Antone Bilbie',
      type: 1,
      manufacturer: 'Park Swayte',
      chassisDesigner: 'Valentina Quesne',
      state: 1,
      apparition: 'Last Samurai, The',
      color: 'red',
    },
    {
      id: '662f74ac-deda-489c-851d-387d48426f9a',
      name: 'in',
      character: 'Auroora Cochet',
      type: 2,
      manufacturer: 'Richmond Goodier',
      chassisDesigner: 'Gerardo Diviney',
      state: 5,
      apparition: 'History of the World: Part I',
      color: 'goldenrod',
    },
    {
      id: 'c50260ce-3ecc-4093-94c8-c32f6af1e016',
      name: 'quis',
      character: 'Jard Lashford',
      type: 2,
      manufacturer: 'Randolph Spurr',
      chassisDesigner: 'Bridget Pinchon',
      state: 2,
      apparition: 'Battle of Britain, The (Why We Fight, 4)',
      color: 'yellow',
    },
    {
      id: '96c1fdd7-659b-4ad4-9d19-265ab1123549',
      name: 'dictumst',
      character: 'Wilow Cleugher',
      type: 1,
      manufacturer: 'Terrill Vasilevich',
      chassisDesigner: 'Selena Summerlee',
      state: 2,
      apparition: 'Multiplicity',
      color: 'pink',
    },
    {
      id: '7088439a-5dab-48f3-b39c-6bc179b97a00',
      name: 'cras',
      character: 'Simonne Brauns',
      type: 1,
      manufacturer: 'Linzy Dugan',
      chassisDesigner: 'Elise Birchill',
      state: 2,
      apparition: 'Executive Protection (Livvakterna)',
      color: 'blue',
    },
    {
      id: 'b13c3866-0147-4bf7-90b1-42317a363cdb',
      name: 'dolor',
      character: 'Gerardo Ovitts',
      type: 1,
      manufacturer: 'Shaughn Ishak',
      chassisDesigner: 'Ram Beiderbecke',
      state: 7,
      apparition: 'Downstairs',
      color: 'turquoise',
    },
    {
      id: '61063167-918d-4c39-b063-44e7f7b52683',
      name: 'interdum',
      character: 'Tailor Caser',
      type: 2,
      manufacturer: 'Morganica Pettegree',
      chassisDesigner: 'Orville Clash',
      state: 5,
      apparition: 'Son of Lassie',
      color: 'green',
    },
    {
      id: '93514b5e-1e79-4e99-aa69-8f7320aaa0a2',
      name: 'non',
      character: 'Renato Maryman',
      type: 1,
      manufacturer: 'Cris Broschek',
      chassisDesigner: 'Zelig Grimmett',
      state: 7,
      apparition: 'Angela',
      color: 'red',
    },
    {
      id: '93b9865a-5892-4265-9fae-f294beb0d993',
      name: 'aenean',
      character: 'Phedra Pymm',
      type: 1,
      manufacturer: 'Sean Durbyn',
      chassisDesigner: 'Pauletta Basso',
      state: 3,
      apparition: 'Burmese Harp, The (Biruma no tategoto)',
      color: 'khaki',
    },
    {
      id: '422bd0a7-92f4-4e77-8049-8c88a403195d',
      name: 'libero',
      character: 'Octavius Ferneyhough',
      type: 2,
      manufacturer: 'Dennie Amorine',
      chassisDesigner: 'Ferrell Flippen',
      state: 5,
      apparition: 'Endangered Species',
      color: 'indigo',
    },
    {
      id: '41b68e9e-bf59-40c1-acad-b769e0355aaa',
      name: 'nibh',
      character: 'Kelci Sandle',
      type: 3,
      manufacturer: 'Tomasine De la Perrelle',
      chassisDesigner: 'Carrie Duchant',
      state: 5,
      apparition: 'Death of a Nation - The Timor Conspiracy',
      color: 'mauv',
    },
    {
      id: '57267e75-d1ca-4deb-989c-c6dd3eafa83c',
      name: 'ante',
      character: 'Marthe Piesold',
      type: 1,
      manufacturer: 'Lorraine Babb',
      chassisDesigner: 'Frances Elsmore',
      state: 3,
      apparition: 'Same Love, Same Rain (El mismo amor, la misma lluvia)',
      color: 'turquoise',
    },
    {
      id: '80f64954-a211-42d5-b9b9-3229754726e6',
      name: 'volutpat',
      character: 'Berty Timbrell',
      type: 3,
      manufacturer: 'Leanor Ledingham',
      chassisDesigner: 'Juliette Deniso',
      state: 6,
      apparition: 'Pursuit to Algiers',
      color: 'mauv',
    },
    {
      id: '23ca6549-7427-4201-aec3-ff0f91cfdce3',
      name: 'molestie',
      character: 'Devi Godding',
      type: 3,
      manufacturer: 'Frayda Elliman',
      chassisDesigner: 'Deane Wallas',
      state: 1,
      apparition: 'Casting Couch',
      color: 'fuscia',
    },
    {
      id: 'c63e24e6-6dc3-4dcf-9c54-1f29cb27f459',
      name: 'congue',
      character: 'Jenifer Stoffels',
      type: 3,
      manufacturer: 'Eyde Abramchik',
      chassisDesigner: 'Morgen Beadel',
      state: 4,
      apparition: '8MM',
      color: 'khaki',
    },
    {
      id: 'd0153166-b197-4df8-8ebd-d065750b7fc2',
      name: 'lorem',
      character: 'Cheryl Kadar',
      type: 2,
      manufacturer: 'Armando Juszczak',
      chassisDesigner: 'Ulrica Mergue',
      state: 5,
      apparition: "Boccaccio '70",
      color: 'khaki',
    },
    {
      id: '589b66b5-6fa1-497e-a2b5-69cf6c13dbf7',
      name: 'sit',
      character: 'Lyn Blomefield',
      type: 3,
      manufacturer: 'Ilsa Slewcock',
      chassisDesigner: 'Bret Allso',
      state: 7,
      apparition: "What to Expect When You're Expecting",
      color: 'purple',
    },
    {
      id: '3e9af3b1-3041-4166-9a34-4eb53c1a3162',
      name: 'dolor',
      character: 'Claudianus Borgnol',
      type: 2,
      manufacturer: 'Kerby Harnor',
      chassisDesigner: 'Coralyn Threader',
      state: 1,
      apparition: 'Lipton Cockton in the Shadows of Sodoma',
      color: 'khaki',
    },
    {
      id: '070151d1-3cd9-4d92-a0c6-f0439353a19c',
      name: 'luctus',
      character: 'Koressa MacNeish',
      type: 2,
      manufacturer: 'Anne-corinne Browell',
      chassisDesigner: 'Josephina Ruprich',
      state: 6,
      apparition: 'National Treasure: Book of Secrets',
      color: 'pink',
    },
    {
      id: '6fded44a-f472-4f71-8683-5f21e04e5f9d',
      name: 'at',
      character: 'Billy Simoncello',
      type: 2,
      manufacturer: 'Richy Abby',
      chassisDesigner: 'Thom Bryns',
      state: 6,
      apparition: 'Splinter',
      color: 'khaki',
    },
    {
      id: 'a12a6d95-b0a0-45cc-9f9f-ac3a7942b111',
      name: 'malesuada',
      character: 'Wallache Deuss',
      type: 3,
      manufacturer: 'Carlota Hatherill',
      chassisDesigner: 'Jaquenetta Kenninghan',
      state: 6,
      apparition: 'Good Job:  Stories of the FDNY, A',
      color: 'violet',
    },
    {
      id: '0f65637d-c82c-43b7-aede-6073a72dbf4b',
      name: 'aliquam',
      character: 'Livvie Herity',
      type: 3,
      manufacturer: 'Shelley Tregona',
      chassisDesigner: "Charmane O'Hannigan",
      state: 2,
      apparition: 'Meeting Evil',
      color: 'yellow',
    },
    {
      id: '72bf175c-9c55-446c-953a-a2b7bf1028be',
      name: 'eu',
      character: 'Dulcinea Jacquot',
      type: 2,
      manufacturer: 'Joanne Mallabund',
      chassisDesigner: 'Niven Stoll',
      state: 3,
      apparition: 'Loins of Punjab Presents',
      color: 'maroon',
    },
    {
      id: 'f21b75bb-1b6f-4bdc-a665-9a17d940032e',
      name: 'sit',
      character: 'Win Dobson',
      type: 3,
      manufacturer: 'Lynn Marshman',
      chassisDesigner: 'Zeke Iceton',
      state: 3,
      apparition: 'So Undercover',
      color: 'yellow',
    },
    {
      id: '945e1e19-b394-4107-bea7-6d73ba8d6a72',
      name: 'morbi',
      character: 'Thibaud Shildrick',
      type: 3,
      manufacturer: 'Philis Sutterfield',
      chassisDesigner: 'Peggy Burbage',
      state: 7,
      apparition: 'Apartment, The',
      color: 'yellow',
    },
    {
      id: 'c5e81909-e06d-4585-95f6-897524d6eb16',
      name: 'nulla',
      character: 'Archibald Thaine',
      type: 2,
      manufacturer: 'Martelle Tucknutt',
      chassisDesigner: 'Madelon Mussalli',
      state: 4,
      apparition: 'Messiah of Evil',
      color: 'puce',
    },
    {
      id: '4b6818f8-ba1f-4421-89c2-003f07ebc8b4',
      name: 'duis',
      character: 'Monika Conelly',
      type: 1,
      manufacturer: 'Lorri Bollini',
      chassisDesigner: 'Phaidra Wisedale',
      state: 5,
      apparition: 'Drei Stunden',
      color: 'mauv',
    },
    {
      id: 'ff406887-6c0b-4799-a97f-602578ddee48',
      name: 'ipsum',
      character: 'Vanya Wakeling',
      type: 2,
      manufacturer: 'Rosemary Blogg',
      chassisDesigner: 'Linette Dack',
      state: 1,
      apparition: "Satan's Sword II (Daibosatsu toge: Ryujin no maki)",
      color: 'fuscia',
    },
    {
      id: '2d001309-f354-43c4-87a9-e1ba87780ff4',
      name: 'vestibulum',
      character: 'Parry Smellie',
      type: 1,
      manufacturer: 'Moyra Kilshaw',
      chassisDesigner: 'Emalee Cockshut',
      state: 4,
      apparition: 'Open Season',
      color: 'green',
    },
    {
      id: 'fdbd3d58-31c6-4d0a-ade1-9335f155cb6a',
      name: 'nisi',
      character: 'Ema Faulkener',
      type: 3,
      manufacturer: 'Johnnie Nail',
      chassisDesigner: 'Benoite Manes',
      state: 7,
      apparition: 'Bogowie',
      color: 'green',
    },
    {
      id: '568d7405-8561-4fa7-aacd-ddabec5f0ee0',
      name: 'ante',
      character: 'Daisey Swindles',
      type: 2,
      manufacturer: 'Patten Pourvoieur',
      chassisDesigner: 'Benton Baffin',
      state: 1,
      apparition: 'Tycoon',
      color: 'orange',
    },
    {
      id: 'b184c5a4-9fa8-477a-99d6-28e0ca286bc9',
      name: 'massa',
      character: 'Berenice Keddy',
      type: 2,
      manufacturer: 'Allistir Ganley',
      chassisDesigner: 'Gene Garrow',
      state: 1,
      apparition: 'Pickpocket',
      color: 'teal',
    },
    {
      id: '24f55764-88b8-492d-81f4-230acdbc07d9',
      name: 'adipiscing',
      character: "Aloysius D'Almeida",
      type: 3,
      manufacturer: 'Robert Griss',
      chassisDesigner: 'Guthrie Handrik',
      state: 2,
      apparition: 'Samurai Assassin (Samurai)',
      color: 'maroon',
    },
    {
      id: '746367bb-fc5c-4406-b6ae-d3def80833b5',
      name: 'gravida',
      character: 'Buckie Greatland',
      type: 1,
      manufacturer: 'Dinah Franey',
      chassisDesigner: 'Kippie Tourle',
      state: 6,
      apparition: 'My First Mister',
      color: 'khaki',
    },
    {
      id: '978d2a56-8c7d-4022-855b-74b6d3df6d34',
      name: 'posuere',
      character: 'Cybil Maidment',
      type: 3,
      manufacturer: 'Briny Conford',
      chassisDesigner: 'Junie Tant',
      state: 6,
      apparition: 'Hatari!',
      color: 'red',
    },
    {
      id: '4be0cf91-0b8f-4c8f-90ec-78e409bcbc88',
      name: 'fusce',
      character: "Saul O'Calleran",
      type: 1,
      manufacturer: 'Merrick Broomhall',
      chassisDesigner: 'Bibi Jessard',
      state: 2,
      apparition: 'Forty Guns',
      color: 'purple',
    },
    {
      id: 'cba720e6-6919-4869-bd1a-9964abd36b2b',
      name: 'odio',
      character: 'Antonino Dudgeon',
      type: 1,
      manufacturer: 'Royall Mandrier',
      chassisDesigner: 'Armand Cree',
      state: 4,
      apparition: 'Up the River',
      color: 'maroon',
    },
    {
      id: 'c17c3670-8a12-40a6-874e-54655db3669c',
      name: 'nisl',
      character: 'Carrol Barlas',
      type: 3,
      manufacturer: 'Claudina Beetles',
      chassisDesigner: 'Reuben McAlarney',
      state: 6,
      apparition: 'Mr. Woodcock',
      color: 'khaki',
    },
    {
      id: '000c376b-9ee5-44c1-a281-575aed833ecb',
      name: 'nulla',
      character: 'Lowell Darkin',
      type: 2,
      manufacturer: 'Odie Hutchinson',
      chassisDesigner: 'Jordain Pymar',
      state: 4,
      apparition: 'One Percent, The',
      color: 'goldenrod',
    },
    {
      id: 'bf757528-5987-404e-8c71-49d3f78a3f57',
      name: 'sapien',
      character: 'Alvin Peizer',
      type: 3,
      manufacturer: 'Barbey Mazzilli',
      chassisDesigner: 'Bradan Cridlan',
      state: 5,
      apparition: 'Pyramid, The',
      color: 'purple',
    },
    {
      id: '070de062-c9f9-4f18-b767-628fb13c116a',
      name: 'feugiat',
      character: 'Janene Wildes',
      type: 1,
      manufacturer: 'Blinnie Rooze',
      chassisDesigner: 'Nedi Spriggs',
      state: 2,
      apparition: 'Ring of Terror',
      color: 'maroon',
    },
    {
      id: '3e1ab3be-50cf-40d7-a500-5e9e9d353111',
      name: 'amet',
      character: 'Nesta Shevlane',
      type: 3,
      manufacturer: 'Natala Gaiter',
      chassisDesigner: 'Olia Nazaret',
      state: 4,
      apparition: 'Brother',
      color: 'maroon',
    },
    {
      id: '64f32c13-3d85-4b02-b848-727629acdb7d',
      name: 'nibh',
      character: 'Rosemarie McGarrahan',
      type: 1,
      manufacturer: 'Salim Wivell',
      chassisDesigner: 'Ferrel Brownscombe',
      state: 3,
      apparition: 'Invisible War, The',
      color: 'maroon',
    },
    {
      id: '1b44ba65-cc4c-4b12-85b3-1adabcc8cf72',
      name: 'vulputate',
      character: 'Beverie Britt',
      type: 1,
      manufacturer: 'Dean Quinney',
      chassisDesigner: 'Rozina Dumbare',
      state: 4,
      apparition: 'In the Loop',
      color: 'puce',
    },
    {
      id: 'aab60f52-28ba-4c24-b39b-88a8991d6311',
      name: 'curae',
      character: 'Teodor Wythe',
      type: 3,
      manufacturer: 'Kirbee Bullick',
      chassisDesigner: 'Urbain Stearne',
      state: 3,
      apparition: 'Partners',
      color: 'orange',
    },
    {
      id: '4c8869bb-0d3f-487e-aa67-692c2e014bb4',
      name: 'adipiscing',
      character: 'Aubry Messier',
      type: 1,
      manufacturer: 'Jackquelin Colliber',
      chassisDesigner: 'Bettine Stife',
      state: 4,
      apparition: 'Oceans (Océans)',
      color: 'maroon',
    },
    {
      id: 'a371d884-575c-4977-a8ac-ebcccfa2f336',
      name: 'at',
      character: 'Ellene Renish',
      type: 2,
      manufacturer: 'Brittaney Lemonnier',
      chassisDesigner: 'Lisbeth Todarello',
      state: 4,
      apparition: 'Memphis Belle',
      color: 'violet',
    },
    {
      id: '98c1ebae-ddad-4559-a9af-291cba87660a',
      name: 'tempus',
      character: 'Bondie Reboulet',
      type: 2,
      manufacturer: 'Stan De Zamudio',
      chassisDesigner: 'Kori Leftwich',
      state: 3,
      apparition: 'Kariera Nikosia Dyzmy',
      color: 'turquoise',
    },
    {
      id: '009b5c5d-54fc-4c0a-862d-a2a98bb37a5f',
      name: 'vestibulum',
      character: 'Connor Stores',
      type: 2,
      manufacturer: 'Marco Fivey',
      chassisDesigner: 'Ellen Dalby',
      state: 6,
      apparition: 'Killjoy 3',
      color: 'crimson',
    },
    {
      id: '9c352913-82db-4d96-b0e9-662b9d211a82',
      name: 'turpis',
      character: 'Kesley Moger',
      type: 3,
      manufacturer: 'Herrick Curreen',
      chassisDesigner: 'Towney Thomsson',
      state: 5,
      apparition: 'Piano Tuner of Earthquakes, The',
      color: 'goldenrod',
    },
    {
      id: '86ba787a-9a0e-43d5-9ab0-3bbd300d2c5a',
      name: 'ante',
      character: 'Daniella Phizackarley',
      type: 1,
      manufacturer: 'Damiano Malyj',
      chassisDesigner: 'Pip Wisam',
      state: 4,
      apparition: "Actor's Revenge, An (Yukinojô henge)",
      color: 'mauv',
    },
    {
      id: '95ccca3a-7ade-44ca-a4ff-71092cedef7b',
      name: 'in',
      character: 'Simone Pidler',
      type: 3,
      manufacturer: 'Abbie Unger',
      chassisDesigner: 'Latisha Tonry',
      state: 2,
      apparition: 'Hard Word, The',
      color: 'blue',
    },
    {
      id: 'bcff4755-4413-420e-bf6a-1c5de7e90bc7',
      name: 'vestibulum',
      character: 'Fair Tather',
      type: 3,
      manufacturer: 'Helsa Pountain',
      chassisDesigner: 'Sidonnie Wilflinger',
      state: 1,
      apparition: "'Hellboy': The Seeds of Creation",
      color: 'blue',
    },
    {
      id: '3e039eba-b0da-47c2-b07a-7dfa8e3dade0',
      name: 'pede',
      character: 'Leonard Van Zon',
      type: 2,
      manufacturer: 'Tiebold Acock',
      chassisDesigner: 'Haroun Lidgard',
      state: 7,
      apparition: 'Elektra Luxx',
      color: 'purple',
    },
    {
      id: 'd4447d93-c9f1-48c9-9a9a-c0270883c592',
      name: 'at',
      character: 'Fulvia Saveall',
      type: 2,
      manufacturer: 'Sheffy Cotgrove',
      chassisDesigner: 'Rosy Clell',
      state: 6,
      apparition: 'Silent Rage',
      color: 'turquoise',
    },
    {
      id: '26858555-f962-4526-946a-255a1cc60f06',
      name: 'sapien',
      character: 'Miof mela Sheed',
      type: 3,
      manufacturer: 'Didi Yezafovich',
      chassisDesigner: 'Les Spittle',
      state: 3,
      apparition: 'Betrayal',
      color: 'maroon',
    },
    {
      id: 'b55d82bd-93ed-4406-b7ea-5d3ebfb5e355',
      name: 'penatibus',
      character: 'Corrinne Greest',
      type: 1,
      manufacturer: 'Meredith Iglesia',
      chassisDesigner: 'Lulita MacKinnon',
      state: 4,
      apparition: 'Die, Monster, Die!',
      color: 'teal',
    },
    {
      id: '36b25261-aa04-415f-824c-ad123baf40bc',
      name: 'maecenas',
      character: 'Blanche Vanyushin',
      type: 1,
      manufacturer: 'Stormi Chaimson',
      chassisDesigner: 'Taite Paling',
      state: 7,
      apparition: 'Last Chance: Diary of Comedians, The (Bokutachi no koukan nikki)',
      color: 'orange',
    },
    {
      id: '3d7320f9-66b3-406d-a852-d785158df9cf',
      name: 'mauris',
      character: 'Armand Frowen',
      type: 2,
      manufacturer: "Karola O'Bradane",
      chassisDesigner: 'Cornie Kirke',
      state: 2,
      apparition: "I'll Cry Tomorrow",
      color: 'goldenrod',
    },
    {
      id: '3030d238-1c00-469d-9f23-74dd3b8fc8ee',
      name: 'sed',
      character: 'Leoline Farquar',
      type: 3,
      manufacturer: 'Rudolfo Menchenton',
      chassisDesigner: 'Flynn Scarr',
      state: 6,
      apparition: 'Lucky Lady',
      color: 'aquamarine',
    },
    {
      id: 'bf056d63-4b5c-4924-a1bf-9068a6facbd0',
      name: 'pede',
      character: 'Olivie Worrell',
      type: 3,
      manufacturer: 'Hedvige Rhodus',
      chassisDesigner: 'Raul Ingram',
      state: 5,
      apparition: 'Maid in Sweden',
      color: 'goldenrod',
    },
    {
      id: 'bcaa1b52-c7d1-4925-827d-f3919b8a8c0d',
      name: 'in',
      character: 'Mateo Danielovitch',
      type: 3,
      manufacturer: 'Timofei Keyser',
      chassisDesigner: 'Sancho Galletley',
      state: 1,
      apparition: 'Dances With the Dragons ( Yu long gong wu)',
      color: 'violet',
    },
    {
      id: '29880015-a294-47dc-8ce1-609785e4faff',
      name: 'natoque',
      character: 'Papagena Standall',
      type: 3,
      manufacturer: 'Karlyn Dancy',
      chassisDesigner: 'Walton Muddiman',
      state: 5,
      apparition: 'Fire on the Mountain',
      color: 'blue',
    },
    {
      id: '94e6a58d-6797-41d6-8824-0f10f80fd76f',
      name: 'in',
      character: 'Michaeline Hentzeler',
      type: 1,
      manufacturer: 'Derry Donovan',
      chassisDesigner: 'Ardelia Dabourne',
      state: 1,
      apparition: 'Amityville: A New Generation',
      color: 'turquoise',
    },
    {
      id: '6eb7ce2f-9725-4ea5-9c74-20677da57216',
      name: 'id',
      character: 'Anabal Gillions',
      type: 1,
      manufacturer: 'Kitti Rue',
      chassisDesigner: 'Killie Arnoult',
      state: 4,
      apparition: 'Strangers in Good Company',
      color: 'blue',
    },
    {
      id: 'b3d62a5d-5de4-4165-8566-ecc69d76634d',
      name: 'nulla',
      character: 'Ruben Roon',
      type: 3,
      manufacturer: 'Brietta Sired',
      chassisDesigner: 'Sander Dilleway',
      state: 7,
      apparition: "Whores' Glory",
      color: 'aquamarine',
    },
    {
      id: 'd215a318-1c05-41d2-991c-ffcc84a4149a',
      name: 'nulla',
      character: 'Winona Goom',
      type: 1,
      manufacturer: 'Cloe Lamp',
      chassisDesigner: 'Alix Fayer',
      state: 3,
      apparition: 'Citizen Koch',
      color: 'goldenrod',
    },
    {
      id: 'ec3c3e60-597d-45b4-a497-c561990199ab',
      name: 'cursus',
      character: 'Norrie Pallatina',
      type: 3,
      manufacturer: 'Yolanthe Ilden',
      chassisDesigner: 'Davey Lapidus',
      state: 2,
      apparition: 'Darjeeling Limited, The',
      color: 'red',
    },
    {
      id: 'cdca8238-8aee-4d1a-a8d0-4f5c5b0d14a1',
      name: 'vulputate',
      character: 'Yolande Arnaudin',
      type: 2,
      manufacturer: 'Stacey De Simone',
      chassisDesigner: 'Lazar Immer',
      state: 5,
      apparition: 'Cheyenne Social Club, The',
      color: 'green',
    },
    {
      id: '4d54b2aa-7671-4f50-9d15-a939814a5cd8',
      name: 'nascetur',
      character: 'Lisle Marley',
      type: 3,
      manufacturer: 'Tatum Pencot',
      chassisDesigner: 'Hermann Tween',
      state: 1,
      apparition: 'Girl Next Door, The',
      color: 'violet',
    },
    {
      id: '22fa3a8c-1496-49e3-ad55-5eafe9281e4a',
      name: 'maecenas',
      character: 'Normand Van der Brug',
      type: 1,
      manufacturer: 'Patty Markussen',
      chassisDesigner: 'Boote Benettelli',
      state: 3,
      apparition: 'It Came from Hollywood',
      color: 'aquamarine',
    },
    {
      id: '18ae44a1-3b5b-48dd-8f25-3f9231007042',
      name: 'vulputate',
      character: 'Trefor Kaser',
      type: 2,
      manufacturer: 'Delaney MacLeese',
      chassisDesigner: 'Keary Savile',
      state: 5,
      apparition: 'Pizzas',
      color: 'yellow',
    },
    {
      id: '889157d9-55bf-4677-853e-4a86bde510a9',
      name: 'donec',
      character: 'Davis Essberger',
      type: 2,
      manufacturer: 'Iolanthe Finkle',
      chassisDesigner: 'Drucy Aldersley',
      state: 5,
      apparition: 'Wedding Singer, The',
      color: 'puce',
    },
    {
      id: '58627a4a-3b91-4e56-82e0-d02ef30d7b18',
      name: 'nisi',
      character: 'Natty Fruchter',
      type: 3,
      manufacturer: 'Neda McKeag',
      chassisDesigner: 'Danya Brunskill',
      state: 2,
      apparition: 'Late Marriage (Hatuna Meuheret)',
      color: 'puce',
    },
    {
      id: 'd4661d6a-e721-48da-8c4e-ea54f668d71d',
      name: 'nibh',
      character: 'Kalila Prisk',
      type: 1,
      manufacturer: 'Onofredo Saundercock',
      chassisDesigner: 'Frankie Gordge',
      state: 6,
      apparition: 'Warsaw Bridge (Pont de Varsòvia)',
      color: 'purple',
    },
    {
      id: 'eb631210-6342-480c-a4db-1457c0b49f77',
      name: 'sem',
      character: 'Karyn Haney',
      type: 1,
      manufacturer: 'Chaunce Pavelka',
      chassisDesigner: 'Kin Locarno',
      state: 3,
      apparition: 'Jinxed!',
      color: 'red',
    },
    {
      id: 'fcec1237-3c7f-4c49-a247-4a486e0ee360',
      name: 'aliquet',
      character: 'Dulce Chittie',
      type: 3,
      manufacturer: 'Gerhardine Layne',
      chassisDesigner: 'Hallie Pudsey',
      state: 2,
      apparition: 'Sword of the Stranger (Sutorejia: Mukô hadan)',
      color: 'maroon',
    },
    {
      id: '2dae4fd4-a057-4ed6-af41-9fa900b9052d',
      name: 'eget',
      character: 'Cassie Bullimore',
      type: 2,
      manufacturer: 'Benjamin Pellant',
      chassisDesigner: 'Rudd McNysche',
      state: 1,
      apparition: 'Patriot, The',
      color: 'green',
    },
    {
      id: 'dae7f13e-1b3b-4abb-9d75-6ce3a6bb3fb8',
      name: 'montes',
      character: 'Sarge Genders',
      type: 3,
      manufacturer: 'Kordula Masding',
      chassisDesigner: 'Jammal Djokic',
      state: 4,
      apparition: 'Once Bitten',
      color: 'fuscia',
    },
    {
      id: '9524bb47-6f2b-45c0-b650-05f98b36a503',
      name: 'ac',
      character: 'Florenza Broadbent',
      type: 1,
      manufacturer: 'Lian Blunn',
      chassisDesigner: 'Ettore Banks',
      state: 1,
      apparition: 'Love and Pigeons',
      color: 'green',
    },
    {
      id: 'aad2bddf-77aa-4428-8700-0f7636cb789f',
      name: 'nunc',
      character: 'Kathryne Overthrow',
      type: 2,
      manufacturer: 'Electra Iacobini',
      chassisDesigner: 'Bail Fontell',
      state: 2,
      apparition: 'Inhale',
      color: 'mauv',
    },
    {
      id: 'dd7ef6b3-4176-42f7-9e4e-927c65450241',
      name: 'vestibulum',
      character: 'Bernardo Jacombs',
      type: 1,
      manufacturer: 'Aprilette Crummey',
      chassisDesigner: 'Darya Whitlaw',
      state: 3,
      apparition: 'Death of a Cyclist (Muerte de un ciclista)',
      color: 'green',
    },
    {
      id: 'ca5c5295-f175-481d-8ccd-35cc432d4304',
      name: 'ultrices',
      character: 'Gwenore Arnaldi',
      type: 1,
      manufacturer: 'Karola Winley',
      chassisDesigner: 'Chevy Robillart',
      state: 4,
      apparition: 'SherryBaby',
      color: 'puce',
    },
    {
      id: '54f292d2-002b-460d-8e8c-1577b02bd1dd',
      name: 'vehicula',
      character: 'Gerome Gunning',
      type: 3,
      manufacturer: 'Adolphe Arnolds',
      chassisDesigner: 'Berrie Audenis',
      state: 6,
      apparition: 'I Am the Law',
      color: 'fuscia',
    },
    {
      id: '8500d6df-e4d7-48cb-b016-55cc7e665526',
      name: 'mattis',
      character: 'Kristoffer Mardlin',
      type: 2,
      manufacturer: 'Berton Leach',
      chassisDesigner: 'Ave Cansdill',
      state: 5,
      apparition: 'PoliWood',
      color: 'mauv',
    },
    {
      id: '629363ab-f6ed-4a1b-9946-54c054829fcb',
      name: 'ultrices',
      character: 'Gannie Marl',
      type: 3,
      manufacturer: 'Glenine Tirkin',
      chassisDesigner: 'Em Dedman',
      state: 7,
      apparition: "The Stranger's Return",
      color: 'puce',
    },
    {
      id: 'bf3c0e1d-eef2-4841-8c37-10d33ed801fc',
      name: 'blandit',
      character: 'Kassey Elrick',
      type: 2,
      manufacturer: 'Jada Crannell',
      chassisDesigner: 'Murvyn Taylo',
      state: 4,
      apparition: 'Snoopy Come Home',
      color: 'maroon',
    },
  ];
};
